// <auto-generated />
namespace MultiType.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create));
        
        string IMigrationMetadata.Id
        {
            get { return "201409192315502_Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
